# Telecom Customer Churn Analytics & Prediction

## Notebook 3: Feature Engineering & Data Preprocessing

### Objective

The objective of this notebook is to prepare the cleaned telecom dataset for machine learning.

The preprocessing steps include:

- Understanding feature engineering
- Dropping unnecessary columns
- Encoding categorical variables
- Feature scaling
- Separating features and target
- Train-Test Split
- Preparing the final dataset for machine learning algorithms

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv('../Data/processed/telecom_churn_clean.csv')

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [6]:
df.shape

(7043, 21)

In [7]:
df.drop('customerID',axis=1,inplace=True)

**The customerID column was removed because
it is a unique identifier and does not contribute meaningful information for predicting customer churn.
Including identifier columns can introduce noise without improving model performance.**

In [9]:
for col in df.select_dtypes(include='object').columns:
    print(f'{col} --> {df[col].unique()}')
    print('-'*50)

gender --> ['Female' 'Male']
--------------------------------------------------
Partner --> ['Yes' 'No']
--------------------------------------------------
Dependents --> ['No' 'Yes']
--------------------------------------------------
PhoneService --> ['No' 'Yes']
--------------------------------------------------
MultipleLines --> ['No phone service' 'No' 'Yes']
--------------------------------------------------
InternetService --> ['DSL' 'Fiber optic' 'No']
--------------------------------------------------
OnlineSecurity --> ['No' 'Yes' 'No internet service']
--------------------------------------------------
OnlineBackup --> ['Yes' 'No' 'No internet service']
--------------------------------------------------
DeviceProtection --> ['No' 'Yes' 'No internet service']
--------------------------------------------------
TechSupport --> ['No' 'Yes' 'No internet service']
--------------------------------------------------
StreamingTV --> ['No' 'Yes' 'No internet service']
--------------------------------------------------
StreamingMovies --> ['No' 'Yes' 'No internet service']
--------------------------------------------------
Contract --> ['Month-to-month' 'One year' 'Two year']
--------------------------------------------------
PaperlessBilling --> ['Yes' 'No']
--------------------------------------------------
PaymentMethod --> ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
--------------------------------------------------
Churn --> ['No' 'Yes']
--------------------------------------------------

In [10]:
binary_cols = [
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling",
    "Churn"
]

## Apply Label Encoding

In [12]:
le = LabelEncoder()

for col in binary_cols:
    df[col] = le.fit_transform(df[col])

In [13]:
df[binary_cols].head()

   gender  Partner  Dependents  PhoneService  PaperlessBilling  Churn
0       0        1           0             0                 1      0
1       1        0           0             1                 0      0
2       1        0           0             1                 1      1
3       1        0           0             0                 0      0
4       0        0           0             1                 1      1

In [14]:
for col in binary_cols:
    print(col, ":", df[col].unique())

gender : [0 1]
Partner : [1 0]
Dependents : [0 1]
PhoneService : [0 1]
PaperlessBilling : [1 0]
Churn : [0 1]

## Label Encoding

Binary categorical variables were converted into numerical values using Label Encoding.

The following features were encoded:

- gender
- Partner
- Dependents
- PhoneService
- PaperlessBilling
- Churn (Target Variable)

Label Encoding was selected because these variables contain only two categories, making binary numerical representation appropriate without introducing ambiguity.

## One Hot Encoding

In [17]:
multi_cols = [
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaymentMethod"
]

df = pd.get_dummies(
    df,
    columns=multi_cols,
    drop_first=True,
    dtype=int
)

In [18]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,0,...,0,0,0,0,0,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,0,0,0,0,0,1,0,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,1,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,1,0,0,0,0,1,0,0,0,0
4,0,0,0,0,2,1,1,70.70,151.65,1,...,0,0,0,0,0,0,0,0,1,0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7043 non-null   int32
 1   SeniorCitizen                          7043 non-null   int64
 2   Partner                                7043 non-null   int32
 3   Dependents                             7043 non-null   int32
 4   tenure                                 7043 non-null   int64
 5   PhoneService                           7043 non-null   int32
 6   PaperlessBilling                       7043 non-null   int32
 7   MonthlyCharges                         7043 non-null   float64
 8   TotalCharges                           7043 non-null   float64
 9   Churn                                  7043 non-null   int32
 10  MultipleLines_No phone service         7043 non-null   int32
 11  MultipleLines_Yes                      7043 non-null   int32
 12  InternetService_Fiber optic            7043 non-null   int32
 13  InternetService_No                     7043 non-null   int32
 14  OnlineSecurity_No internet service     7043 non-null   int32
 15  OnlineSecurity_Yes                     7043 non-null   int32
 16  OnlineBackup_No internet service       7043 non-null   int32
 17  OnlineBackup_Yes                       7043 non-null   int32
 18  DeviceProtection_No internet service   7043 non-null   int32
 19  DeviceProtection_Yes                   7043 non-null   int32
 20  TechSupport_No internet service        7043 non-null   int32
 21  TechSupport_Yes                        7043 non-null   int32
 22  StreamingTV_No internet service        7043 non-null   int32
 23  StreamingTV_Yes                        7043 non-null   int32
 24  StreamingMovies_No internet service    7043 non-null   int32
 25  StreamingMovies_Yes                    7043 non-null   int32
 26  Contract_One year                      7043 non-null   int32
 27  Contract_Two year                      7043 non-null   int32
 28  PaymentMethod_Credit card (automatic)  7043 non-null   int32
 29  PaymentMethod_Electronic check         7043 non-null   int32
 30  PaymentMethod_Mailed check             7043 non-null   int32
dtypes: float64(2), int32(27), int64(2)
memory usage: 963.0 KB

In [20]:
df.select_dtypes(include="object").columns

Index([], dtype='object')

## One-Hot Encoding

Multi-category categorical variables were transformed using One-Hot Encoding with `pd.get_dummies()`.

The following features were encoded:

- MultipleLines
- InternetService
- OnlineSecurity
- OnlineBackup
- DeviceProtection
- TechSupport
- StreamingTV
- StreamingMovies
- Contract
- PaymentMethod

The parameter `drop_first=True` was used to avoid the Dummy Variable Trap by removing one redundant category from each encoded feature. The resulting dataset contains only numerical variables, making it suitable for machine learning algorithms.

## Feature Scaling

In [23]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

In [24]:
print(X.shape)
print(y.shape)

(7043, 30)
(7043,)

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,
    test_size=0.20,
    random_state=42,
    stratify=y)

In [26]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (5634, 30)
X_test : (1409, 30)
y_train: (5634,)
y_test : (1409,)

In [27]:
numeric_cols = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

In [28]:
scaler = StandardScaler()

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [57]:
import joblib

joblib.dump(scaler, "../models/scaler.pkl")

print("Scaler saved successfully!")

Scaler saved successfully!

In [29]:
X_train.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,MultipleLines_No phone service,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
3738,1,0,0,0,0.102371,0,0,-0.521976,-0.262257,1,...,0,0,1,0,1,0,0,0,1,0
3151,1,0,1,1,-0.711743,1,0,0.337478,-0.503635,0,...,0,0,0,0,0,0,0,0,0,1
4860,1,0,1,1,-0.793155,0,0,-0.809013,-0.749883,1,...,1,0,0,0,0,0,1,0,0,1
3867,0,0,1,0,-0.263980,1,1,0.284384,-0.172722,0,...,0,0,1,0,1,0,1,1,0,0
3810,1,0,1,1,-1.281624,1,0,-0.676279,-0.989374,0,...,0,0,0,0,0,0,0,0,1,0

## Data Preprocessing

The cleaned dataset was prepared for machine learning using the following steps:

- Removed the identifier column (`customerID`).
- Applied Label Encoding to binary categorical variables.
- Applied One-Hot Encoding to multi-category variables.
- Split the dataset into training (80%) and testing (20%) sets using stratified sampling.
- Standardized the numerical features (`tenure`, `MonthlyCharges`, and `TotalCharges`) using `StandardScaler` fitted only on the training data to prevent data leakage.

In [31]:
processed_train = X_train.copy()
processed_train["Churn"] = y_train

processed_test = X_test.copy()
processed_test["Churn"] = y_test

processed_train.to_csv(
    "../Data/processed/train_data.csv",
    index=False
)

processed_test.to_csv(
    "../Data/processed/test_data.csv",
    index=False
)